language: ruby
services: postgresql
bundler_args: --without development --deployment
rvm:
- 2.0.0
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- export RAILS_ENV=test
- psql --version
before_script:
- cp -f config/travis/database.yml config/database.yml
- cp -f config/travis/application.yml config/application.yml
- bundle exec rake db:create db:migrate
script: bundle exec rspec --format=d
addons:
  code_climate:
    repo_token: 600186b44c043a8fbcd009d7a386fcd1f125613607e84a7629cabd7278f3760c
  postgresql: 9.3